services:
  dns_db:
    image: postgres:17-alpine
    container_name: dns_db
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: dns
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  dns_bot:
    build: .
    container_name: dns_bot
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ${DNS_REAL_PROFILE_PATH:-./data/browser_profile}:/app/dns_real_profile
      - ./data:/app/data
    environment:
      TZ: Europe/Moscow
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  prometheus:
    image: prom/prometheus:v3.11.0
    container_name: dns_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:12.4.2
    container_name: dns_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus

volumes:
  pgdata:
  prometheus_data:
  grafana_data:

networks:
  backend_network:
    external: true



