services:
  db:
    image: postgres:16-alpine
    container_name: dns_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dns
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: dns_bot
    volumes:
      - /home/vgribv/dns_real_profile:/app/dns_real_profile
    network_mode: "host"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}

volumes:
  pgdata:


