spring.application.name=DNSparser
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true
spring.autoconfigure.exclude=org.telegram.telegrambots.longpolling.starter.TelegramBotStarterConfiguration


bot.token=${BOT_TOKEN}
proxy.hostname=${PROXY_HOST}
proxy.port=${PROXY_PORT}

project.path=${user.dir}/
dns.link.prefix=https://www.dns-shop.ru/catalog/markdown/
dns.link.products.filters=https://www.dns-shop.ru/catalogMarkdown/markdown/products-filters/
dns.link.referer=https://www.dns-shop.ru
dns.link.ajax.state=https://www.dns-shop.ru/ajax-state/product-buy/
