spring.application.name=DNSparser
spring.datasource.url=jdbc:postgresql://192.168.31.48:5432/dns?reWriteBatchedStatements=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true

bot.token=${BOT_TOKEN}
proxy.hostname=127.0.0.1
proxy.port=1111

project.path=${user.dir}/
dns.link.prefix=https://www.dns-shop.ru/catalog/markdown/
dns.link.products.filters=https://www.dns-shop.ru/catalogMarkdown/markdown/products-filters/
dns.link.referer=https://www.dns-shop.ru
dns.link.ajax.state=https://www.dns-shop.ru/ajax-state/product-buy/
