name: Deploy to Home Xubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy
        run: |
          docker compose up -d --build