name: Deploy to Home Xubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PROXY_HOST: ${{ secrets.PROXY_HOST }}
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
          DNS_REAL_PROFILE_PATH: ${{ secrets.DNS_REAL_PROFILE_PATH }}
        run: |
          echo "BOT_TOKEN=${BOT_TOKEN}" > .env
          echo "BOT_NAME=${BOT_NAME}" >> .env
          echo "DB_URL=${DB_URL}" >> .env
          echo "DB_USERNAME=${DB_USERNAME}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "PROXY_HOST=${PROXY_HOST}" >> .env
          echo "PROXY_PORT=${PROXY_PORT}" >> .env
          echo "GRAFANA_PASSWORD=${GRAFANA_PASSWORD}" >> .env
          echo "DNS_REAL_PROFILE_PATH=${DNS_REAL_PROFILE_PATH}" >> .env
          
          cat <<EOF > docker-compose.override.yml
          services:
            dns_db:
              image: alpine
              entrypoint: ["sh", "-c", "sleep infinity"]
              ports: []
          EOF
          
          docker compose up -d --build